mode:  # Operation mode flags
    RANDOM_EVENT: True  # Determines if we select a random event or iterate through each
    RANDOM_ANGLE: True  # Determines if we select a random angle or do a complete sweep
    VARY_POINT: True  # Determines if we vary the prod point or set it to (0,0)
    WEIGHT_POINT: True  # Determines if we weight point selection by T^6 in event - Needs VARYPOINT.
jet_parameters:  # Parameters for the jets to be run
    NUM_JETS: 10  # Number of jets to produce
    JET_ENERGY: 100  # Jet energy in GeV
moment_parameters:  # Parameters to select moment properties
    MOMENT_K: 0  # Which k-moment to calculate - NON-FUNCTIONAL - just uses k=0
    TEMP_CUTOFF: 0  # Temperature at which to set plasma integrand to 0. Basically hadronization temp.
global_constants:  # Physical constants to be set by the user.
    G: 2  # Coupling constant for strong interaction