mode:  # Operation mode flags
    RANDOM_EVENT: True  # Determines if we select a random event or iterate through each
    RANDOM_ANGLE: True  # Determines if we select a random angle or do a complete sweep
    VARY_POINT: True  # Determines if we vary the prod point or set it to (0,0)
    WEIGHT_POINT: True  # Determines if we weight point selection by T^6 in event - Needs VARYPOINT.
    NUM_EVENTS: 1  # Number of events to generate -- 0 runs events until interrupt.
    NUM_SAMPLES: 100  # Number of hard jet production processes to run in each event
    KEEP_EVENT: False  # Keep plasma data for future analysis
transport:  # Parameters for the jets to be run
    TAU_FS: 0.5  # freestreaming time in fm. Default 0.5 fm.
    GRID_STEP: 0.1  # Hydro / Trento grid step in fm. Default 0.15*NUCLEON_WIDTH from DukeQCD BA
    TIME_STEP: 0.05  # Hydro / Trento time step in fm. Default 0.25*GRID_STEP fm from DukeQCD BA
    GRID_MAX_TARGET: 15  # Maximum hydro grid width.
    T_END: 0.110  # Minimum temperature in GeV of all cells at which to cut off hydro evolution.
    T_HRG: 0.155  # Temperature in GeV at which to consider the medium hadronized
    T_UNHYDRO: 0.150  # Temperature in GeV at which to consider the medium unhydrodynamic
trento:
    NORM: 5.84  # Overall normalization factor for reduced thickness function (and thereby multiplicity)
    PROJ1: 'Pb'  # Collisions species 1
    PROJ2: 'Pb'  # Collisions species 2
    NUCLEON_WIDTH: 0.5  # Gaussian nucleon width in fm. Default 0.5 fm from DukeQCD BA
    CROSS_SECTION: 7.0  # Inelastic nucleon-nucleon cross section sigma_{NN} in fm^2
    BMIN: None  # Minimum impact parameter. For no limits, set None.
    BMAX: None  # Maximum impact parameter. For no limits, set None.
jet:  # Parameters for the jets to be run
    JET_ENERGY: 22.5  # Jet energy in GeV - corresponds to TOTAL jet E, not just charged particle E
    E_FLUCT: True  # Vary jet energy EBE? - If True, JET_ENERGY does nothing.
    E_IS: True  # Importance sample jet energy - uses uniform approximate distribution
    MIN_JET_ENERGY: 1  # Minimum jet energy in GeV to use if jet energy fluctuates. - Min 1.25 if RHIC sampling
    MAX_JET_ENERGY: 60
    TAU: 0.01  # Timestep used for jet propagation
    RECORD: False  # Save xarray jet record?
global_constants:  # Physical constants to be set by the user.
    G: 2.13  # Coupling constant for IN-MEDIUM strong interaction
    G_MU: 2.13  # Coupling constant for debye mass strong interaction
    K_BBMG: 250  # Coupling constant for BBMG energy loss - Current default 250 ???
    K_DRIFT: 1  # Scale factor for flow drift effect - default realistic estimate is 1
    K_FG_DRIFT: 1  # Scale factor for flow-gradient drift effects - default realistic estimate is 1
    ROOT_S: 5020  # sqrt(s) in GeV of collision system - used for scale running calculations
