mode:  # Operation mode flags
    RANDOM_EVENT: True  # Determines if we select a random event or iterate through each
    RANDOM_ANGLE: True  # Determines if we select a random angle or do a complete sweep
    VARY_POINT: True  # Determines if we vary the prod point or set it to (0,0)
    WEIGHT_POINT: True  # Determines if we weight point selection by T^6 in event - Needs VARYPOINT.
    NUM_EVENTS: 2  # Number of events to generate -- 0 runs events until interrupt.
    NUM_SAMPLES: 5  # Number of jets to run in each event
transport_parameters:  # Parameters for the jets to be run
    TAU_FS: 0.5  # freestreaming time in fm. Default 0.5 fm.
    GRID_STEP: 0.1  # Hydro grid step in fm. Default 0.1 fm from trial and error.
    T_END: 0.110  # Minimum temperature in GeV of all cells at which to cut off hydro evolution.
    T_HRG: 0.200  # Temperature in GeV at which to consider the medium hadronized
    T_UNHYDRO: 0.150  # Temperature in GeV at which to consider the medium unhydrodynamic
jet_parameters:  # Parameters for the jets to be run
    JET_ENERGY: 100  # Jet energy in GeV
moment_parameters:  # Parameters to select moment properties
    MOMENT_K: 0  # Which k-moment to calculate - NON-FUNCTIONAL - just uses k=0
global_constants:  # Physical constants to be set by the user.
    G: 2  # Coupling constant for strong interaction